#' Perform Quality Checks on ELAN Text Exports
#'
#' Reads the subject/month/activity selection from \code{processed/reference.tsv}
#' (generated by \code{fetch_ids.R}) to locate ELAN \code{.txt} files under a
#' synchronized OneDrive/SharePoint "Reach & Grasp" directory, runs
#' \code{qc.all()} from \code{qc_functions.R} on each file, and writes:
#' \itemize{
#'   \item \code{quality_check_summary.log}: console log (appended).
#'   \item \code{failed_files.tsv}: structured list of files that failed QC.
#'   \item \code{qc_offset.tsv}: files with non-unique last offsets.
#'   \item \code{qc_continuous.tsv}: onset/offset mismatch records.
#'   \item \code{qc_labels.tsv}: labels that break casing/rule conventions.
#' }
#'
#' @details
#' The script locates the OneDrive root automatically (Windows/macOS) or accepts
#' an explicit override via environment variable \code{CHLA_BEHAVIOR_CODING_PATH}.
#' Missing folders are skipped and reported. Output directories are created if
#' absent. The summary sink is safely closed even if errors occur.
#'
#' @section Prerequisites:
#' \enumerate{
#'   \item OneDrive folder \strong{Reach & Grasp} is synced.
#'   \item \code{fetch_ids.R} has been run; \code{processed/reference.tsv} exists.
#'   \item \code{qc_functions.R} resides in \code{Reach & Grasp/Quality Check} and defines \code{qc.all()}.
#' }
#'
#' @section Robustness:
#' Missing directories are warned and skipped; permission issues during listing
#' are caught. If \code{failed_files.tsv} is locked by another process, the
#' results are written to a temporary file and a warning is issued.
#'
#' @seealso \code{fs::dir_ls}, \code{purrr::map}, \code{stringr::str_detect}
#' @author
#' Maintainer: Jinseok Oh <joh@chla.usc.edu>

# An elegant way to install packages
if (!(requireNamespace("Require", quietly = TRUE))) install.packages("Require")
package_list <- c("fs", "stringr", "purrr",
                  "dplyr", "here", "lubridate", "future.apply")
Require::Require(package_list, require = TRUE)

# wake-up call (run if needed)
here::i_am("qc_project.Rproj")

################
# PATH details #
################
# This code should be sitting in '/Reach & Grasp/Quality Check' folder
qc_files_path <- here()
processed_path <- file.path(dirname(here()), "processed")
qc_state_dir <- file.path(processed_path, "qc_state")

# QC mode switch (0=incremental, 1=full)
today <- today()
first_day <- floor_date(today, unit = "month")
# Find first Monday of the month (%% 7 keeps day 1 when it is already a Monday)
first_monday <- first_day + days((8 - wday(first_day, week_start = 1)) %% 7)
# Check if today is within that week (Mon-Fri)
qc_full <- if (today >= first_monday && today <= first_monday + days(4)) 1 else 0

# Prefer qc_state outputs for incremental
ref_new <- file.path(qc_state_dir, "reference_new.tsv")
ref_log <- file.path(qc_state_dir, "reference_log.tsv")
reference_path <- if (qc_full == 1 && file.exists(ref_log)) ref_log else ref_new

cat("Using reference file:", reference_path, "\n")
if (!file.exists(reference_path)) {
  stop("Reference file not found. Run fetch_ids.R first.")
}
# This should be updated and saved as reference_log.tsv later
references <- read.csv(reference_path, sep = "\t", stringsAsFactors = FALSE)

# Quit if no new video coding output to review
if (!qc_full && nrow(references) == 0) {
  cat("No new assignments since last run. Skipping QC. \n")
  quit(status = 0)
}

run_stamp <- format(now(), "%Y-%m-%d_%H%M%S")
qc_by_date <- file.path(
  processed_path,
  paste0("qc_performed_", run_stamp)
)
dir.create(qc_by_date, showWarnings = FALSE, recursive = TRUE)

# You also need to load this R script to use functions I wrote.
source(file.path(qc_files_path, "qc_functions.R"))

#########################
# FILE GATHERING & LOGS #
#########################
subdirs <- unique(references$path)
txtpaths <- file.path(dirname(here()), subdirs)
existing_txtpaths <- txtpaths[dir.exists(txtpaths)]

# Warn about missing directories
missing_log_path <- file.path(qc_by_date,
                              "missing_files_and_folders.log")
missing_txtpaths <- txtpaths[!dir.exists(txtpaths)]
if (length(missing_txtpaths) > 0) {
  writeLines(c("===== Missing Directores =====",
               fs::path_file(missing_txtpaths)),
    missing_log_path
  )
}

# List and filter .txt files only from existing directories
txt_files_all <- existing_txtpaths |>
  purrr::map(~tryCatch(fs::dir_ls(.x, type = "file", glob = "*.txt"),
                       error = function(e) character(0))) |>
  unlist(use.names = FALSE)

# Filter for wanted prefixes
wanted_regex <- paste0("^(", paste(references$prefix, collapse = "|"),
                       ")_.*\\.txt$")
txt_files <- txt_files_all[stringr::str_detect(fs::path_file(txt_files_all),
                                               wanted_regex)]
###########################
# SINGLE-PASS PARALLEL QC #
###########################
plan(multisession)

process_qc <- function(txt, out_dir) {
  # source(here::here("qc_functions.R"))
  bn <- fs::path_file(txt)
  prefix <- stringr::str_extract(bn, "TD\\d+-M\\d+A\\d+")

  result <- tryCatch({
    out <- qc.all(txt)

    # Immediate logging of specific issues to files
    if (!out$last_offsets_match)
      write(bn, file.path(out_dir, paste0(bn, "_offset_error.txt")))
    if (!(length(out$continuously_coded) == 1 &&
        out$continuously_coded == "No onset-offset mismatch found")) {
      write.csv(out$continuously_coded,
        file.path(out_dir,
                  paste0(bn, "_cont_issues.csv")),
        row.names = FALSE
      )
    }
    if (nrow(out$proper_labels) > 0) {
      write.csv(out$proper_labels,
                file.path(out_dir, paste0(bn, "_label_issues.csv")),
                row.names = FALSE)
    }
    # Return a success list with the data you need later
    list(success = TRUE,
         filename = txt,
         prefix = prefix,
         key = bn,
         data = out,
         error = NULL)
  }, error = function(e) {
    err_msg <- stringr::str_split(conditionMessage(e), ";")[[1]]
    list(success = FALSE,
         filename = txt,
         prefix = prefix,
         key = bn,
         data = NULL,
         error = tail(err_msg, 1))
  })
  return(result)
}

all_results <- future_lapply(txt_files,
                             process_qc,
                             out_dir = qc_by_date)

# ---- Summarize QC results by coder ----
# Update Reference Log (Vectorized)
success_prefixes <- purrr::map_chr(keep(all_results, ~ .x$success), ~ .x$prefix)
matches <- references$prefix %in% success_prefixes
references$last_qc[matches] <- as.character(today)
references$was_reviewed[matches] <- TRUE

# Merge into the existing log instead of overwriting it.
# An incremental run loads only the new rows (reference_new.tsv);
# writing those alone to reference_log.tsv would erase the history,
# and fetch_ids.R would then re-flag every old assignment as new.
if (file.exists(ref_log)) {
  ref_log_tab <- read.delim(ref_log, sep = "\t", stringsAsFactors = FALSE)
  ref_log_tab <- dplyr::bind_rows(
    ref_log_tab[!(ref_log_tab$prefix %in% references$prefix), , drop = FALSE],
    references
  )
} else {
  ref_log_tab <- references
}
write.table(ref_log_tab, ref_log, sep = "\t", row.names = FALSE, quote = FALSE)

# Coder: extract 2-3 uppercase letter coder ID
extract_coder <- function(x) {
  fname <- fs::path_file(x)
  m <- stringr::str_match(fname, ".*_([A-Z]{2,3})\\.txt$")[, 2]
  # fallback: take the last token before .txt and strip non-letters
  ifelse(is.na(m),
         stringr::str_replace(stringr::str_extract(fname, "[^_]+(?=\\.txt$)"),
                              "[^A-Za-z]", ""),
         m)
}

dump_section <- function(out_file, title, df){
    writeLines(paste0("\n===== ", title, " ====="),
               con = out_file,
               sep = "\n",
               useBytes = TRUE)
    if (is.null(df) || nrow(df) == 0){
        writeLines("(none)\n", con = out_file, sep = "\n", useBytes = TRUE)
    } else {
        # Write as TSV blocks inside the txt file
        write.table(df, file=out_file, sep="\t",
                    row.names = FALSE, col.names = TRUE, quote = FALSE)
        writeLines("", con = out_file, useBytes = TRUE)
    }
}

# 1. Reconstruct the global data frames from the 'all_results' list
success_data <- keep(all_results, ~ .x$success)

offset_with_coder <- success_data |>
  keep(~ !.x$data$last_offsets_match) |>
  map_df(~ data.frame(filename = .x$key, coder = extract_coder(.x$key)))
# If there's none, at least provide a coder column
if (nrow(offset_with_coder) == 0) {
  offset_with_coder <- data.frame(
    filename = character(),
    coder = character()
  )
}

labels_with_coder <- success_data |>
  map_df(~ {
    df <- .x$data$proper_labels
    if (nrow(df) > 0) {
      df$filename <- .x$key
      df$coder <- extract_coder(.x$key)
    }
    df
  })
if (nrow(labels_with_coder) == 0) {
  labels_with_coder["filename"] = character()
  labels_with_coder["coder"] = character()
}

continuous_with_coder <- success_data |>
  map_df(~ {
    res <- .x$data$continuously_coded
    if (!(length(res) == 1 && res == "No onset-offset mismatch found")) {
      df <- as.data.frame(res)
      df$filename <- .x$key
      df$coder <- extract_coder(.x$key)
      return(df)
    }
    return(data.frame(filename = character(),
                      coder = character()))
  })

# Build the failed-file table from the parallel results so unreadable
# files (e.g. cloud-only placeholders that failed to download) are
# reported instead of dropped silently.
failed_data <- keep(all_results, ~ !.x$success) |>
  map_df(~ data.frame(filename = .x$filename, error = .x$error,
                      stringsAsFactors = FALSE))
if (nrow(failed_data) > 0) {
  write.table(failed_data, file.path(qc_by_date, "failed_files.tsv"),
              sep = "\t", row.names = FALSE, quote = FALSE)
  failed_log_coded <- failed_data |> mutate(coder = extract_coder(filename))
} else {
  failed_log_coded <- data.frame(filename = character(), error = character(),
                                 coder = character())
}

# 2. Identify Problematic Coders
problem_coders <- sort(unique(na.omit(c(
  failed_log_coded$coder,
  offset_with_coder$coder,
  labels_with_coder$coder,
  continuous_with_coder$coder
))))
problem_coders <- problem_coders[problem_coders != ""]

# 3. Create Dumps
qc_by_coder_dir <- file.path(qc_by_date, "qc_by_coder")
dir.create(qc_by_coder_dir,
           showWarnings = FALSE,
           recursive = TRUE)

if (length(problem_coders) > 0) {
  for (cd in problem_coders) {
    out_file <- file.path(qc_by_coder_dir, paste0("qc_issues_", cd, ".txt"))
    con <- file(out_file, open="wt", encoding="UTF-8")

    writeLines(c(
      paste0("QC issues for coder: ", cd),
      paste0("Generated at: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
      paste0("Processed path: ", processed_path)
      ), con = con, useBytes = TRUE)

    dump_section(con, "Failed Files (System Errors)", dplyr::filter(failed_log_coded, coder == cd))
    dump_section(con, "Offset Issues", dplyr::filter(offset_with_coder, coder == cd))
    dump_section(con, "Label Issues", dplyr::filter(labels_with_coder, coder == cd))
    dump_section(con, "Continuous Coding Issues", dplyr::filter(continuous_with_coder, coder == cd))

    close(con)
  }
}

plan(sequential)
