#' Perform Quality Checks on ELAN Text Exports
#'
#' Reads the subject/month/activity selection from \code{processed/reference.tsv}
#' (generated by \code{fetch_ids.R}) to locate ELAN \code{.txt} files under a
#' synchronized OneDrive/SharePoint "Reach & Grasp" directory, runs
#' \code{qc.all()} from \code{qc_functions.R} on each file, and writes:
#' \itemize{
#'   \item \code{quality_check_summary.log}: console log (appended).
#'   \item \code{failed_files.tsv}: structured list of files that failed QC.
#'   \item \code{qc_offset.tsv}: files with non-unique last offsets.
#'   \item \code{qc_continuous.tsv}: onset/offset mismatch records.
#'   \item \code{qc_labels.tsv}: labels that break casing/rule conventions.
#' }
#'
#' @details
#' The script locates the OneDrive root automatically (Windows/macOS) or accepts
#' an explicit override via environment variable \code{CHLA_BEHAVIOR_CODING_PATH}.
#' Missing folders are skipped and reported. Output directories are created if
#' absent. The summary sink is safely closed even if errors occur.
#'
#' @section Prerequisites:
#' \enumerate{
#'   \item OneDrive folder \strong{Reach & Grasp} is synced.
#'   \item \code{fetch_ids.R} has been run; \code{processed/reference.tsv} exists.
#'   \item \code{qc_functions.R} resides in \code{Reach & Grasp/Quality Check} and defines \code{qc.all()}.
#' }
#'
#' @section QC modes:
#' Weekly runs are incremental: a file is (re)checked only if its assignment
#' is new, has never passed QC, or the file was modified after its last
#' successful QC (a re-uploaded correction). A full QC re-checks everything
#' in the reference log. Full mode triggers automatically during the week of
#' the month's first Monday, or on demand:
#' \code{Rscript perform_qc.R --full} (or \code{Sys.setenv(QC_FULL="1")}
#' before sourcing in RStudio); \code{--incremental} / \code{QC_FULL=0}
#' force incremental.
#'
#' @section Robustness:
#' Missing directories are warned and skipped; permission issues during listing
#' are caught. If \code{failed_files.tsv} is locked by another process, the
#' results are written to a temporary file and a warning is issued.
#'
#' @seealso \code{fs::dir_ls}, \code{purrr::map}, \code{stringr::str_detect}
#' @author
#' Maintainer: Jinseok Oh <joh@chla.usc.edu>

# An elegant way to install packages
if (!(requireNamespace("Require", quietly = TRUE))) install.packages("Require")
package_list <- c("fs", "stringr", "purrr",
                  "dplyr", "here", "lubridate", "future.apply")
Require::Require(package_list, require = TRUE)

# wake-up call (run if needed)
here::i_am("qc_project.Rproj")

################
# PATH details #
################
# This code should be sitting in '/Reach & Grasp/Quality Check' folder
qc_files_path <- here()
processed_path <- file.path(dirname(here()), "processed")
qc_state_dir <- file.path(processed_path, "qc_state")

# QC mode switch (0=incremental, 1=full)
today <- today()
first_day <- floor_date(today, unit = "month")
# Find first Monday of the month (%% 7 keeps day 1 when it is already a Monday)
first_monday <- first_day + days((8 - wday(first_day, week_start = 1)) %% 7)
# Check if today is within that week (Mon-Fri)
qc_full <- if (today >= first_monday && today <= first_monday + days(4)) 1 else 0

# Manual override: `Rscript perform_qc.R --full` / `--incremental`,
# or Sys.setenv(QC_FULL="1") / "0" when sourcing from RStudio
cli_args <- commandArgs(trailingOnly = TRUE)
if ("--full" %in% cli_args || Sys.getenv("QC_FULL") == "1") qc_full <- 1
if ("--incremental" %in% cli_args || Sys.getenv("QC_FULL") == "0") qc_full <- 0
cat("QC mode:", if (qc_full) "FULL" else "INCREMENTAL", "\n")

ref_new <- file.path(qc_state_dir, "reference_new.tsv")
ref_log <- file.path(qc_state_dir, "reference_log.tsv")

read_ref <- function(p) {
  if (file.exists(p)) read.delim(p, sep = "\t", stringsAsFactors = FALSE)
  else NULL
}
ref_new_tab <- read_ref(ref_new)
ref_log_tab <- read_ref(ref_log)
if (is.null(ref_new_tab) && is.null(ref_log_tab)) {
  stop("No reference files found in ", qc_state_dir,
       ". Run fetch_ids.R first.")
}

# Work list = new assignments plus everything already in the log.
# Per assignment, `check_after` decides which of its files need (re)checking:
#   NA        -> check unconditionally (new, never passed QC, or full QC)
#   timestamp -> check only files modified after it (re-uploaded corrections)
references <- dplyr::bind_rows(
  ref_new_tab,
  if (!is.null(ref_log_tab) && !is.null(ref_new_tab)) {
    ref_log_tab[!(ref_log_tab$prefix %in% ref_new_tab$prefix), , drop = FALSE]
  } else {
    ref_log_tab
  }
)
if (!"last_qc" %in% names(references)) references$last_qc <- NA_character_
if (!"was_reviewed" %in% names(references)) references$was_reviewed <- FALSE
references$check_after <- if (qc_full) {
  NA_character_
} else {
  ifelse(references$was_reviewed %in% TRUE, references$last_qc, NA_character_)
}

# You also need to load this R script to use functions I wrote.
source(file.path(qc_files_path, "qc_functions.R"))

#########################
# FILE GATHERING & LOGS #
#########################
subdirs <- unique(references$path)
txtpaths <- file.path(dirname(here()), subdirs)
existing_txtpaths <- txtpaths[dir.exists(txtpaths)]
missing_txtpaths <- txtpaths[!dir.exists(txtpaths)]

# List .txt files with modification times. Listing does not hydrate
# OneDrive cloud-only placeholders; only files selected for QC get read.
txt_info <- existing_txtpaths |>
  purrr::map(~tryCatch(fs::dir_info(.x, type = "file", glob = "*.txt"),
                       error = function(e) NULL)) |>
  dplyr::bind_rows()

# Keep files that belong to an assignment on the work list and are
# new, never passed QC, or modified since their last successful QC
if (nrow(txt_info) > 0) {
  file_prefix <- stringr::str_extract(fs::path_file(txt_info$path),
                                      "TD\\d+-M\\d+A\\d+")
  row_idx <- match(file_prefix, references$prefix)
  # handles both date-only (old logs) and full timestamps
  check_after <- lubridate::parse_date_time(
    references$check_after[row_idx],
    orders = c("Ymd HMS", "Ymd"), tz = Sys.timezone(), quiet = TRUE
  )
  needs_qc <- !is.na(row_idx) &
    (is.na(check_after) | txt_info$modification_time > check_after)
  txt_files <- as.character(txt_info$path[needs_qc])
} else {
  txt_files <- character(0)
}

if (length(txt_files) == 0 && length(missing_txtpaths) == 0) {
  cat("Nothing new or modified since the last QC. Skipping. \n")
  quit(status = 0)
}
cat("Files to check:", length(txt_files), "\n")

run_stamp <- format(now(), "%Y-%m-%d_%H%M%S")
qc_by_date <- file.path(
  processed_path,
  paste0("qc_performed_", run_stamp)
)
dir.create(qc_by_date, showWarnings = FALSE, recursive = TRUE)

# Warn about missing directories
missing_log_path <- file.path(qc_by_date,
                              "missing_files_and_folders.log")
if (length(missing_txtpaths) > 0) {
  writeLines(c("===== Missing Directores =====",
               fs::path_file(missing_txtpaths)),
    missing_log_path
  )
}
###########################
# SINGLE-PASS PARALLEL QC #
###########################
plan(multisession)

process_qc <- function(txt, out_dir) {
  # source(here::here("qc_functions.R"))
  bn <- fs::path_file(txt)
  prefix <- stringr::str_extract(bn, "TD\\d+-M\\d+A\\d+")

  result <- tryCatch({
    out <- qc.all(txt)

    # Immediate logging of specific issues to files
    if (!out$last_offsets_match)
      write(bn, file.path(out_dir, paste0(bn, "_offset_error.txt")))
    if (!(length(out$continuously_coded) == 1 &&
        out$continuously_coded == "No onset-offset mismatch found")) {
      write.csv(out$continuously_coded,
        file.path(out_dir,
                  paste0(bn, "_cont_issues.csv")),
        row.names = FALSE
      )
    }
    if (nrow(out$proper_labels) > 0) {
      write.csv(out$proper_labels,
                file.path(out_dir, paste0(bn, "_label_issues.csv")),
                row.names = FALSE)
    }
    # Return a success list with the data you need later
    list(success = TRUE,
         filename = txt,
         prefix = prefix,
         key = bn,
         data = out,
         error = NULL)
  }, error = function(e) {
    err_msg <- stringr::str_split(conditionMessage(e), ";")[[1]]
    list(success = FALSE,
         filename = txt,
         prefix = prefix,
         key = bn,
         data = NULL,
         error = tail(err_msg, 1))
  })
  return(result)
}

all_results <- future_lapply(txt_files,
                             process_qc,
                             out_dir = qc_by_date)

# ---- Summarize QC results by coder ----
# Update Reference Log (Vectorized)
success_prefixes <- purrr::map_chr(keep(all_results, ~ .x$success), ~ .x$prefix)
matches <- references$prefix %in% success_prefixes
references$last_qc[matches] <- format(now())
references$was_reviewed[matches] <- TRUE
references$check_after <- NULL

# Merge into the existing log instead of overwriting it.
# An incremental run loads only the new rows (reference_new.tsv);
# writing those alone to reference_log.tsv would erase the history,
# and fetch_ids.R would then re-flag every old assignment as new.
if (file.exists(ref_log)) {
  ref_log_tab <- read.delim(ref_log, sep = "\t", stringsAsFactors = FALSE)
  ref_log_tab <- dplyr::bind_rows(
    ref_log_tab[!(ref_log_tab$prefix %in% references$prefix), , drop = FALSE],
    references
  )
} else {
  ref_log_tab <- references
}
write.table(ref_log_tab, ref_log, sep = "\t", row.names = FALSE, quote = FALSE)

# Coder: extract 2-3 uppercase letter coder ID
extract_coder <- function(x) {
  fname <- fs::path_file(x)
  m <- stringr::str_match(fname, ".*_([A-Z]{2,3})\\.txt$")[, 2]
  # fallback: take the last token before .txt and strip non-letters
  ifelse(is.na(m),
         stringr::str_replace(stringr::str_extract(fname, "[^_]+(?=\\.txt$)"),
                              "[^A-Za-z]", ""),
         m)
}

dump_section <- function(out_file, title, df){
    writeLines(paste0("\n===== ", title, " ====="),
               con = out_file,
               sep = "\n",
               useBytes = TRUE)
    if (is.null(df) || nrow(df) == 0){
        writeLines("(none)\n", con = out_file, sep = "\n", useBytes = TRUE)
    } else {
        # Write as TSV blocks inside the txt file
        write.table(df, file=out_file, sep="\t",
                    row.names = FALSE, col.names = TRUE, quote = FALSE)
        writeLines("", con = out_file, useBytes = TRUE)
    }
}

# 1. Reconstruct the global data frames from the 'all_results' list
success_data <- keep(all_results, ~ .x$success)

offset_with_coder <- success_data |>
  keep(~ !.x$data$last_offsets_match) |>
  map_df(~ data.frame(filename = .x$key, coder = extract_coder(.x$key)))
# If there's none, at least provide a coder column
if (nrow(offset_with_coder) == 0) {
  offset_with_coder <- data.frame(
    filename = character(),
    coder = character()
  )
}

labels_with_coder <- success_data |>
  map_df(~ {
    df <- .x$data$proper_labels
    if (nrow(df) > 0) {
      df$filename <- .x$key
      df$coder <- extract_coder(.x$key)
    }
    df
  })
if (nrow(labels_with_coder) == 0) {
  labels_with_coder["filename"] = character()
  labels_with_coder["coder"] = character()
}

continuous_with_coder <- success_data |>
  map_df(~ {
    res <- .x$data$continuously_coded
    if (!(length(res) == 1 && res == "No onset-offset mismatch found")) {
      df <- as.data.frame(res)
      df$filename <- .x$key
      df$coder <- extract_coder(.x$key)
      return(df)
    }
    return(data.frame(filename = character(),
                      coder = character()))
  })

# Build the failed-file table from the parallel results so unreadable
# files (e.g. cloud-only placeholders that failed to download) are
# reported instead of dropped silently.
failed_data <- keep(all_results, ~ !.x$success) |>
  map_df(~ data.frame(filename = .x$filename, error = .x$error,
                      stringsAsFactors = FALSE))
if (nrow(failed_data) > 0) {
  write.table(failed_data, file.path(qc_by_date, "failed_files.tsv"),
              sep = "\t", row.names = FALSE, quote = FALSE)
  failed_log_coded <- failed_data |> mutate(coder = extract_coder(filename))
} else {
  failed_log_coded <- data.frame(filename = character(), error = character(),
                                 coder = character())
}

# 2. Identify Problematic Coders
problem_coders <- sort(unique(na.omit(c(
  failed_log_coded$coder,
  offset_with_coder$coder,
  labels_with_coder$coder,
  continuous_with_coder$coder
))))
problem_coders <- problem_coders[problem_coders != ""]

# 3. Create Dumps
qc_by_coder_dir <- file.path(qc_by_date, "qc_by_coder")
dir.create(qc_by_coder_dir,
           showWarnings = FALSE,
           recursive = TRUE)

if (length(problem_coders) > 0) {
  for (cd in problem_coders) {
    out_file <- file.path(qc_by_coder_dir, paste0("qc_issues_", cd, ".txt"))
    con <- file(out_file, open="wt", encoding="UTF-8")

    writeLines(c(
      paste0("QC issues for coder: ", cd),
      paste0("Generated at: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
      paste0("Processed path: ", processed_path)
      ), con = con, useBytes = TRUE)

    dump_section(con, "Failed Files (System Errors)", dplyr::filter(failed_log_coded, coder == cd))
    dump_section(con, "Offset Issues", dplyr::filter(offset_with_coder, coder == cd))
    dump_section(con, "Label Issues", dplyr::filter(labels_with_coder, coder == cd))
    dump_section(con, "Continuous Coding Issues", dplyr::filter(continuous_with_coder, coder == cd))

    close(con)
  }
}

plan(sequential)
